### ISSUE TITLE
[Python] Unable to build: `FileNotFoundError: [Errno 2] No such file or directory: '../Cargo.toml'`

### ISSUE THREAD

**Issue by peku33** [sonos/tract#1348]
Hi,

I'm trying to get tract python package to work on bsd system. While native rust version builds and works fine, the python build script fails early with `FileNotFoundError: [Errno 2] No such file or directory: '../Cargo.toml'`

Full backtrace:
```
Collecting tract
  Downloading tract-0.21.1.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/usr/home/<user>/test/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/home/<user>/test/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/home/<user>/test/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kvmm6xm5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kvmm6xm5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-kvmm6xm5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-kvmm6xm5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/tmp/pip-build-env-kvmm6xm5/overlay/lib/python3.11/site-packages/toml/decoder.py", line 133, in load
          with io.open(_getpath(f), encoding='utf-8') as ffile:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '../Cargo.toml'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I believe that core project files are missing from .tar.gz that is downloaded to build this package from source whenever wheel is not available.

Maybe @kali could have a look?

**Comment by peku33** [comment]
Can confirm it builds with pip, thank you.

However it still fails with poetry:
```
$ poetry add tract==0.21.2.dev0

Updating dependencies
Resolving dependencies... (0.3s)

Package operations: 2 installs, 0 updates, 0 removals

  - Installing numpy (1.26.4)
  - Installing tract (0.21.2.dev0): Failed

  ParseConstraintError

  Could not parse version constraint: >=0.10<0.11

  at .venv/lib/python3.11/site-packages/poetry/core/constraints/version/parser.py:188 in parse_single_constraint
      184│             return VersionUnion(VersionRange(max=version), VersionRange(min=version))
      185│
      186│         return version
      187│
    → 188│     raise ParseConstraintError(f"Could not parse version constraint: {constraint}")
      189│
      190│
      191│ def _make_x_constraint_range(
      192│     version: Version, *, invert: bool = False, is_marker_constraint: bool = False

The following error occurred when trying to handle this error:


  InvalidRequirement

  The requirement is invalid: invalid version constraint ">=0.10<0.11"

  at .venv/lib/python3.11/site-packages/poetry/core/version/requirements.py:71 in __init__
       67│
       68│         try:
       69│             self.constraint = parse_constraint(constraint)
       70│         except ParseConstraintError:
    →  71│             raise InvalidRequirement(
       72│                 f'The requirement is invalid: invalid version constraint "{constraint}"'
       73│             )
       74│
       75│         self.pretty_constraint = constraint

Cannot install tract.
```

**Comment by kali** [comment]
Thanks for checking. You may have noticed I'm not super fluent in Python and Python packaging. Do you have any idea of what is going wrong there ?

**Comment by peku33** [comment]
I bet that this:
https://github.com/sonos/tract/blob/9590809ed661b1175c4f62c9cdf7d5c230e2523c/api/py/pyproject.toml#L1-L7
has incorrect value. IIRC constraints should be separated by `,`. 

/probably/ this could be rewritten to:
```
[build-system]
requires = [
    "setuptools >=68, <69",
    "setuptools_rust >=1.6, <1.7",
    "wheel >=0.41, <0.42",
    "toml >=0.10, <0.11"
]
```

i believe this could be simplified even more by using `~=`

**Comment by kali** [comment]
Hello again! Want to give a shot at `0.21.2.dev1` ?

**Comment by peku33** [comment]
Can confirm this builds and installs with `poetry`, thanks!
