### ISSUE TITLE
Multiple symbols and concretize

### ISSUE THREAD

**Issue by kali** [sonos/tract#383]
Oh, I just tried adapting the snippet you sent yesterday to also have the batch size as streaming dim:

```rust
use tract_core::dim::{Symbol, ToDim};
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(
                u8::datum_type(),
                tvec!(TDim::from('b'), TDim::from('s') * 2),
            ),
        )?
        .into_optimized()?;

    let optimized_model = model
        .concretize_dims(
            &SymbolValues::default()
                .with('s'.into(), 20)
                .with('b'.into(), 1),
        )?
        .optimize()?
        .into_runnable()?;

    let input: Tensor = tract_ndarray::Array2::<u8>::zeros((1, 40)).into();
    println!("{:#?}", optimized_model.run(tvec!(input))?);

    Ok(())
}
```

And I get:

```
    Finished release [optimized] target(s) in 1.75s
     Running `target/release/tractdyn`
thread 'main' panicked at 'Can not work out a data format with two actual symbolic dim', /home/bminixhofer/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-core-0.11.1/src/ops/nn/data_formats.rs:33:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So it looks like it does not work yet (with this model).

_Originally posted by @bminixhofer in https://github.com/sonos/tract/issues/313#issuecomment-713631031_

**Comment by kali** [comment]
I'll have a look.

**Comment by kali** [comment]
Hey @bminixhofer... I think this one should be working now (or at least be close). I know it's been a while, but you may want to give a shot to the trying-to-get-batch-symbolic branch if you still have the model around.

**Comment by bminixhofer** [comment]
Thanks! I still have the model, I'll check if it works.

**Comment by bminixhofer** [comment]
Hey, sorry, I don't see a `trying-to-get-batch-symbolic` branch. With release 0.14.2 I still get the same error.

**Comment by bminixhofer** [comment]
Ok, nevermind, I saw you already merged it. With the code:

`src/main.rs`
```rust
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let batch_symbol = Symbol::new('b');
    let length_symbol = Symbol::new('s');

    let model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(
                u8::datum_type(),
                tvec!(TDim::from(batch_symbol), TDim::from(length_symbol) * 2),
            ),
        )?
        .into_optimized()?;

    let optimized_model = model
        .concretize_dims(
            &SymbolValues::default()
                .with(length_symbol, 20)
                .with(batch_symbol, 1),
        )?
        .optimize()?
        .into_runnable()?;

    let input: Tensor = tract_ndarray::Array2::<u8>::zeros((1, 40)).into();
    println!("{:#?}", optimized_model.run(tvec!(input))?);

    Ok(())
}
```
`Cargo.toml`
```toml
[package]
name = "tracttest"
version = "0.1.0"
edition = "2018"

[dependencies]
tract-onnx = { git = "https://github.com/sonos/tract", branch = "main" }
tract-core = { git = "https://github.com/sonos/tract", branch = "main" }
```

I still get the error:

```
(base) bminixhofer@pop-os:~/Documents/Experiments/tracttest$ cargo run
   Compiling tracttest v0.1.0 (/home/bminixhofer/Documents/Experiments/tracttest)
    Finished dev [unoptimized + debuginfo] target(s) in 3.01s
     Running `target/debug/tracttest`
thread 'main' panicked at 'Can not work out a data format with two actual symbolic dim', /home/bminixhofer/.cargo/git/checkouts/tract-01a3138c7a4b58a3/d5bb976/core/src/ops/nn/data_formats.rs:33:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

should be reproducible with all of the models from here: https://github.com/bminixhofer/nnsplit/tree/8a07d8e934f2e75c46815cc192263f952d34009a/models

**Comment by kali** [comment]
Yeah, merged it friday afternoon, I should have tell you, I apologize. Thanks, anyway, I'll have a look and see what gets in the way now :)

**Comment by kali** [comment]
Ho, the branch is `multiple-symbols`.

**Comment by kali** [comment]
And... tada ! Got this one to work :)

```
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let batch_symbol = Symbol::new('b');
    let length_symbol = Symbol::new('s');

    let model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(
                u8::datum_type(),
                tvec!(TDim::from(batch_symbol), TDim::from(length_symbol) * 2),
            ),
        )?
        .into_optimized()?
        .into_runnable()?;

    let input: Tensor = tract_ndarray::Array2::<u8>::zeros((1, 40)).into();
    println!("{:#?}", model.run(tvec!(input))?);

    Ok(())
}
```

**Comment by bminixhofer** [comment]
That's awesome! I can confirm it works, and seems to lead to a very nice speedup from a quick benchmark (using the same model as above):

```
32 times 1x25           time:   [445.62 ms 446.44 ms 447.22 ms]                          
16 times 2x25           time:   [153.04 ms 153.28 ms 153.68 ms]                          
8 times 4x25            time:   [80.284 ms 80.342 ms 80.403 ms]                         
4 times 8x25            time:   [47.646 ms 47.724 ms 47.804 ms]                         
2 times 16x25           time:   [29.412 ms 29.518 ms 29.627 ms]                          
1 times 32x25           time:   [20.887 ms 20.929 ms 20.972 ms]                          
```

<details><summary>(Code)</summary>

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use ndarray_rand::rand_distr::Uniform;
use ndarray_rand::RandomExt;
use tract_onnx::prelude::*;

fn criterion_benchmark(c: &mut Criterion) -> TractResult<()> {
    let batch_symbol = Symbol::new('b');
    let length_symbol = Symbol::new('s');

    let model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(
                u8::datum_type(),
                tvec!(TDim::from(batch_symbol), TDim::from(length_symbol) * 2),
            ),
        )?
        .into_optimized()?
        .into_runnable()?;

    c.bench_function("32 times 1x25", |b| {
        b.iter(|| {
            for _ in 0..32 {
                model.run(black_box(tvec![Tensor::from(
                    tract_ndarray::Array2::<u8>::random((1, 25), Uniform::new(0, 255))
                )]));
            }
        })
    });
    c.bench_function("16 times 2x25", |b| {
        b.iter(|| {
            for _ in 0..16 {
                model.run(black_box(tvec![Tensor::from(
                    tract_ndarray::Array2::<u8>::random((2, 25), Uniform::new(0, 255))
                )]));
            }
        })
    });
    c.bench_function("8 times 4x25", |b| {
        b.iter(|| {
            for _ in 0..8 {
                model.run(black_box(tvec![Tensor::from(
                    tract_ndarray::Array2::<u8>::random((4, 25), Uniform::new(0, 255))
                )]));
            }
        })
    });
    c.bench_function("4 times 8x25", |b| {
        b.iter(|| {
            for _ in 0..4 {
                model.run(black_box(tvec![Tensor::from(
                    tract_ndarray::Array2::<u8>::random((8, 25), Uniform::new(0, 255))
                )]));
            }
        })
    });
    c.bench_function("2 times 16x25", |b| {
        b.iter(|| {
            for _ in 0..2 {
                model.run(black_box(tvec![Tensor::from(
                    tract_ndarray::Array2::<u8>::random((16, 25), Uniform::new(0, 255))
                )]));
            }
        })
    });
    c.bench_function("1 times 32x25", |b| {
        b.iter(|| {
            model.run(black_box(tvec![Tensor::from(
                tract_ndarray::Array2::<u8>::random((32, 25), Uniform::new(0, 255))
            )]));
        })
    });

    Ok(())
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```
</details>

It's also really nice that `.concretize_dims` is not necessary anymore.
