### ISSUE TITLE
Implement TensorArrayV3

### ISSUE THREAD

**Issue by sheosi** [sonos/tract#468]
Hi all, I've been trying to load a TensorFlow model from the `precise` wake word engine into Tract and got this.

```
thread 'tests::test_positive' panicked at 'called `Result::unwrap()` on an `Err` value: ModelError(Failed analyse for node #74 "net/TensorArray" Unimplemented(TensorArrayV3)

Caused by:
    Wrong nnumber of outputs. Op says 1, node says 2.)', src/lib.rs:251:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::unwrap
             at /home/sergio/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973
   4: tract_precise::tests::test_positive
             at ./src/lib.rs:251
   5: tract_precise::tests::test_positive::{{closure}}
             at ./src/lib.rs:250
   6: core::ops::function::FnOnce::call_once
             at /home/sergio/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
   7: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The model can be found here: [https://github.com/MycroftAI/precise-data/blob/models/hey-mycroft.pb]()

**Comment by kali** [comment]
Hello @sheosi, thanks for your interest in tract.

Unfortunately, we do not support TF TensorArray or ONNX TensorSequence. I am afraid it is not even on the roadmap. It is a big amount of work, and we are not really convinced of the benefits at this stage. Feel free to try and convince us though :)

I don't know if this model have been translated to other forms, but a quick look suggest it could be expressed without sequences or array using ONNX scan operator for instance.

**Comment by sheosi** [comment]
Unfortunately I don't have the know how to do neither, yet thanks for being so open. I'm closing this issue.
