### ISSUE TITLE
Evaluating #2 "ZipMap" Unimplemented(ZipMap)

### ISSUE THREAD

**Issue by linrium** [sonos/tract#650]
I got the `Evaluating #2 "ZipMap" Unimplemented(ZipMap)` error when trying to run the model with input fact is

### Code
```rust
let model = tract_onnx::onnx()
        .model_for_path("<model_link>")
        .unwrap()
        .with_input_fact(
            0,
            InferenceFact::dt_shape(
                DatumType::F32,
                tvec!(1, 15)
            )
        )
        .unwrap()
        .with_output_fact(0, InferenceFact::default())
        .unwrap()
        .into_runnable()
        .unwrap();

let tensor = tract_ndarray::Array2::from_shape_vec((1, 15), vec![0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32, 0f32]).into_tensor();

let result = model.run(tvec!(input)).unwrap();
```

### Model input
```
[name: "float_input"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
      }
      dim {
        dim_value: 15
      }
    }
  }
}
]
```

### Error message
```
Evaluating #2 "ZipMap" Unimplemented(ZipMap)
```

### Version
```toml
tract-onnx = "0.16.1"
```

### Stack trace
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Evaluating #2 "ZipMap" Unimplemented(ZipMap)

Caused by:
    stateless evaluation not implemented

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/backtrace.rs:328:13
   3: std::backtrace::Backtrace::capture
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/backtrace.rs:296:9
   4: anyhow::error::<impl anyhow::Error>::msg
             at /Users/linhtt20/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.55/src/error.rs:79:36
   5: anyhow::private::format_err
             at /Users/linhtt20/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.55/src/lib.rs:665:13
   6: tract_core::ops::EvalOp::eval
             at /Users/linhtt20/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-core-0.16.1/src/ops/mod.rs:81:9
   7: tract_core::plan::eval
             at /Users/linhtt20/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-core-0.16.1/src/plan.rs:468:17
   8: core::ops::function::FnMut::call_mut
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/core/src/ops/function.rs:150:5
   9: tract_core::plan::SimpleState<F,O,M,P>::run_plan_with_eval
             at /Users/linhtt20/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-core-0.16.1/src/plan.rs:248:21
  10: tract_core::plan::SimpleState<F,O,M,P>::run
             at /Users/linhtt20/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-core-0.16.1/src/plan.rs:177:9
  11: tract_core::plan::SimplePlan<F,O,M>::run
             at /Users/linhtt20/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-core-0.16.1/src/plan.rs:115:9
  12: http_server::main
             at ./src/main.rs:49:18
  13: core::ops::function::FnOnce::call_once
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/core/src/ops/function.rs:227:5
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/sys_common/backtrace.rs:122:18
  15: std::rt::lang_start::{{closure}}
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/rt.rs:145:18
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/core/src/ops/function.rs:259:13
  17: std::panicking::try::do_call
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/panicking.rs:492:40
  18: std::panicking::try
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/panicking.rs:456:19
  19: std::panic::catch_unwind
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/panic.rs:137:14
  20: std::rt::lang_start_internal::{{closure}}
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/rt.rs:128:48
  21: std::panicking::try::do_call
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/panicking.rs:492:40
  22: std::panicking::try
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/panicking.rs:456:19
  23: std::panic::catch_unwind
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/panic.rs:137:14
  24: std::rt::lang_start_internal
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/rt.rs:128:20
  25: std::rt::lang_start
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/rt.rs:144:17
  26: _main', src/main.rs:49:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/core/src/result.rs:1065:23
   4: http_server::main
             at ./src/main.rs:49:18
   5: core::ops::function::FnOnce::call_once
             at /rustc/f0c4da49983aa699f715caf681e3154b445fb60b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Note: Sorry, I can't post the model here because the company's policy

**Comment by kali** [comment]
Hello, thanks for your interest in tract.

Unfortunately, tract does not support maps. So ZipMap can not be implemented.

**Comment by linrium** [comment]
Do you have any plans for the future? How can I support adding this feature?

**Comment by kali** [comment]
It is very unlikely we support maps. tract main focus is neural networks: support for so the `-ml` extension of onnx is not a priority, and maps only appears there (and quite marginally). On the other hand, allowing tract to "flow" anything else than tensors would be a huge overall of the entire codebase, and would probably hurt code complexity and performance. So maps (along with tensor lists) are out of the picture. TBH, these are so marginal that I doubt they have their place in ONNX. Other projects in the same design space (like tensorflow lite) make very similar choices, only supporting tensors.

If you want to run this model with tract, you will need to find a way to encode it without maps. It may be feasible:  in my only experience with maps and zipmap they appearred when translating a model from XGBoost or something similar, at the very last stage, when conditioning the output result to a map. We were able to rework the protobuf model in python to keep the useful op (the tree classifier), drop the zipmap and just us the raw result from the classifier...
