### ISSUE TITLE
thread 'main' panicked at 'no entry found for key'

### ISSUE THREAD

**Issue by vessd** [sonos/tract#777]
I created a model using `TensorFlow 2`, converted it to `ONNX` and trying to run it.
`python -m tf2onnx.convert --saved-model tensorflow-model-path --output model.onnx`
```
pub fn load_from_file(path: &Path) -> anyhow::Result<()> {
    let model = tract_onnx::onnx()
        .model_for_path(path)?
        .with_input_fact(0, f32::fact(&[1, 4]).into())?
        .with_input_fact(1, f32::fact(&[1, 10]).into())?
        .with_input_fact(2, f32::fact(&[1, 4]).into())?
        .into_optimized()?
        .into_runnable()?;

    let input = tensor1(&[
        -5.000000000000000000e-01,
        0.000000000000000000e+00,
        -8.888888888888888395e-01,
        -1.200697658318436778e+00,
    ]);
    dbg!(model.run(tvec!(input))?);

    Ok(())
}
```
The code crashes with an error that I don't understand, but this topic is new to me, and maybe I'm doing something wrong.

```
thread 'main' panicked at 'no entry found for key', /home/vagrant/.cargo/git/checkouts/tract-01a3138c7a4b58a3/7aced68/core/src/ops/source.rs:13:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/option.rs:1854:5
   5: core::option::Option<T>::expect
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/option.rs:718:21
   6: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/collections/hash/map.rs:1175:9
   7: <tract_core::ops::source::SourceState as tract_core::ops::OpState>::eval
             at /home/vagrant/.cargo/git/checkouts/tract-01a3138c7a4b58a3/7aced68/core/src/ops/source.rs:13:18
   8: tract_core::plan::eval
             at /home/vagrant/.cargo/git/checkouts/tract-01a3138c7a4b58a3/7aced68/core/src/plan.rs:467:32
   9: core::ops::function::FnMut::call_mut
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:164:5
  10: tract_core::plan::SimpleState<F,O,M,P>::run_plan_with_eval
             at /home/vagrant/.cargo/git/checkouts/tract-01a3138c7a4b58a3/7aced68/core/src/plan.rs:248:21
  11: tract_core::plan::SimpleState<F,O,M,P>::run
             at /home/vagrant/.cargo/git/checkouts/tract-01a3138c7a4b58a3/7aced68/core/src/plan.rs:177:9
  12: tract_core::plan::SimplePlan<F,O,M>::run
             at /home/vagrant/.cargo/git/checkouts/tract-01a3138c7a4b58a3/7aced68/core/src/plan.rs:115:9
  13: correlator::onnx::load_from_file
             at ./src/onnx.rs:35:10
...
```

**Comment by kali** [comment]
Can you share the .onnx file somehow ? Whatever is causing the error, the reporting is subpar.

**Comment by vessd** [comment]
I figured it out. I need to pass a vector of 3 elements to the input. If I pass less, then the error occurs.
Perhaps you should add a check for the length of the input.
